name: ignorium

scripts:

  pub-get:
    run: |
      melos exec --concurrency=1 -- \
      dart pub get
    packageFilters:
      scope:

  pub-outdated:
    run: |
      melos exec --concurrency=1 -- \
      dart pub outdated
    packageFilters:
      scope:

  pub-upgrade:
    run: |
      melos exec --concurrency=1 -- \
      dart pub upgrade
    packageFilters:
      scope:

packages:
  - ./**
  - .

ignore:
  - .dvm/**

ide:
  intellij:
    enabled: false