name: ignorium

version: 0.1.0

license: 'BSD-3-Clause'

repository: https://github.com/ilexbor/ignorium

issue_tracker: https://github.com/ilexbor/ignorium/issues

description: >
  Ignorium is a CLI tool for automatic .gitignore generation based on detected files and their contents.
  Ignorium intelligently scans your project directory and generates appropriate .gitignore files based on detected frameworks, build tools, IDEs, and other project characteristics.

executables:
  ignorium: ignorium

dependencies:
  args: ^2.7.0
  collection: ^1.19.1
  meta: ^1.16.0
  path: ^1.9.1
  quiver: ^3.2.2
  stack_trace: ^1.12.1
  yaml: ^3.1.3

dev_dependencies:
  lintorium: ">=30.0.0"

environment:
  sdk: '>=3.0.0 <4.0.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - git
  - gitignore
  - ignore
