import 'dart:convert';

import 'package:ignorium/src/gitignore/gitignore_buffer.dart';
import 'package:ignorium/src/gitignore/gitignore_codec.dart';

// Example:
//
// # [ignorium] This file was generated by the `ignorium` package.
// # [ignorium] ⚠️ Manual changes may be overwritten.
// # [ignorium] Learn more: https://pub.dev/packages/ignorium.
//
// user-rule-1
// user-rule-2
//
// # [ignorium] [BEGIN AUTO GENERATE SECTION]
//
// # [ignorium] [xcode.workspace]
// xcode.workspace.rule
//
// # [ignorium] [xcode.project]
// xcode.project.rule
//
// # [ignorium] [END AUTO GENERATE SECTION]
//
// user-rule-3
// user-rule-4

class GitignoreBufferDeserializer {
  GitignoreBufferDeserializer({
    GitignoreCodec? codec,
  }) : _codec = codec ?? GitignoreCodec();

  final GitignoreCodec _codec;

  Future<GitignoreBuffer> call(Stream<String> streamOfStrings) async {
    final buffer = GitignoreBuffer();

    final streamOfLines = streamOfStrings.transform(const LineSplitter());

    var autoGenerateSectionBeginCount = 0;
    var autoGenerateSectionEndCount = 0;

    await for (final line in streamOfLines) {
      if (line.startsWith(GitignoreCodec.autoGenerateSectionBegin)) {
        autoGenerateSectionBeginCount++;
        if (autoGenerateSectionBeginCount - autoGenerateSectionEndCount > 1) {
          throw StateError('autoGenerateSectionEndCount != autoGenerateSectionBeginCount');
        }
      }

      if (line.startsWith(GitignoreCodec.autoGenerateSectionEnd)) {
        autoGenerateSectionEndCount++;
        if (autoGenerateSectionEndCount > autoGenerateSectionBeginCount) {
          throw StateError('autoGenerateSectionEndCount != autoGenerateSectionBeginCount');
        }
      }

      if (autoGenerateSectionEndCount != autoGenerateSectionBeginCount) {
        continue;
      }

      if (_codec.containsPrefix(line)) {
        continue;
      }

      buffer.userContent.writeln(line);
    }

    if (autoGenerateSectionEndCount != autoGenerateSectionBeginCount) {
      throw StateError('autoGenerateSectionEndCount != autoGenerateSectionBeginCount');
    }

    return buffer;
  }
}
