import 'package:collection/collection.dart';
import 'package:ignorium/src/gitignore/gitignore_buffer.dart';
import 'package:ignorium/src/gitignore/gitignore_codec.dart';
import 'package:ignorium/src/gitignore/gitignore_ruleset.dart';
import 'package:ignorium/src/gitignore/gitignore_section.dart';

class GitignoreBufferSerializer {
  GitignoreBufferSerializer({
    GitignoreCodec? codec,
  }) : _codec = codec ?? GitignoreCodec();

  final GitignoreCodec _codec;

  String call(GitignoreBuffer buffer) {
    final stringBuffer = StringBuffer();

    _writeUserContent(stringBuffer, buffer.userContentBeforeAutoGenerateSection);
    _writeAutoGenerateRuleSets(stringBuffer, buffer.autoGenerateRuleSets);
    _writeUserContent(stringBuffer, buffer.userContentAfterAutoGenerateSection);

    final string = stringBuffer.toString();

    final result = string.trim().replaceAll(RegExp(r'\n{3,}'), '\n\n');

    return result;
  }

  void _writeUserContent(StringBuffer outputBuffer, StringBuffer content) {
    if (content.isEmpty) {
      return;
    }

    outputBuffer.writeln();
    outputBuffer.writeln(content);
    outputBuffer.writeln();
  }

  void _writeAutoGenerateRuleSets(StringBuffer outputBuffer, Iterable<GitignoreRuleSet> ruleSets) {
    if (ruleSets.isEmpty) {
      return;
    }

    outputBuffer.writeln();
    outputBuffer.writeln(_codec.encodePrefix('[BEGIN AUTO GENERATE SECTION]'));
    outputBuffer.writeln();

    final notice = [
      'This section was generated by the `ignorium` package.',
      '⚠️ Manual changes may be overwritten.',
      'Learn more: https://pub.dev/packages/ignorium.',
    ].map(_codec.encodePrefix);

    outputBuffer.writeAll(notice, '\n');
    outputBuffer.writeln();

    GitignoreSection? prevSection;

    final sortedRuleSets = ruleSets.sorted((a, b) {
      return a.section.name.compareTo(b.section.name);
    });

    for (final ruleSet in sortedRuleSets) {
      if (prevSection == null || ruleSet.section != prevSection) {
        outputBuffer.writeln();
        outputBuffer.writeln(_codec.encodePrefix('[${ruleSet.section}]'));
        prevSection = ruleSet.section;
      }
      for (final rule in ruleSet.rules) {
        outputBuffer.writeln(rule.rule);
      }
    }

    outputBuffer.writeln();
    outputBuffer.writeln(_codec.encodePrefix('[END AUTO GENERATE SECTION]'));
    outputBuffer.writeln();
  }
}
