import 'package:collection/collection.dart';
import 'package:ignorium/src/gitignore/gitignore_buffer.dart';
import 'package:ignorium/src/gitignore/gitignore_codec.dart';
import 'package:ignorium/src/gitignore/gitignore_section.dart';

class GitignoreBufferSerializer {
  GitignoreBufferSerializer({
    GitignoreCodec? codec,
  }) : _codec = codec ?? GitignoreCodec();

  final GitignoreCodec _codec;

  String call(GitignoreBuffer buffer) {
    final stringBuffer = StringBuffer();

    _writeUserContent(stringBuffer, buffer);
    _writeAutoGeneratedSection(stringBuffer, buffer);

    final string = stringBuffer.toString();

    final result = string.trim().replaceAll(RegExp(r'\n{3,}'), '\n\n');

    return result;
  }

  void _writeUserContent(StringBuffer stringBuffer, GitignoreBuffer gitignoreBuffer) {
    if (gitignoreBuffer.userContent.isEmpty) {
      return;
    }

    stringBuffer.writeln();
    stringBuffer.writeln(gitignoreBuffer.userContent);
    stringBuffer.writeln();
  }

  void _writeAutoGeneratedSection(StringBuffer stringBuffer, GitignoreBuffer gitignoreBuffer) {
    if (gitignoreBuffer.ruleSets.isEmpty) {
      return;
    }

    stringBuffer.writeln();
    stringBuffer.writeln(_codec.encodePrefix('[BEGIN AUTO GENERATE SECTION]'));
    stringBuffer.writeln();

    final notice = [
      'This section was generated by the `ignorium` package.',
      '⚠️ Manual changes may be overwritten.',
      'Learn more: https://pub.dev/packages/ignorium.',
    ].map(_codec.encodePrefix);

    stringBuffer.writeAll(notice, '\n');
    stringBuffer.writeln();

    GitignoreSection? prevSection;

    final sortedRuleSets = gitignoreBuffer.ruleSets.sorted((a, b) {
      return a.section.name.compareTo(b.section.name);
    });

    for (final ruleSet in sortedRuleSets) {
      if (prevSection == null || ruleSet.section != prevSection) {
        stringBuffer.writeln();
        stringBuffer.writeln(_codec.encodePrefix('[${ruleSet.section}]'));
        prevSection = ruleSet.section;
      }
      for (final rule in ruleSet.rules) {
        stringBuffer.writeln(rule.rule);
      }
    }

    stringBuffer.writeln();
    stringBuffer.writeln(_codec.encodePrefix('[END AUTO GENERATE SECTION]'));
    stringBuffer.writeln();
  }
}
